### ISSUE TITLE
profileViewController got a bug

### ISSUE THREAD

**Issue by iceman201** [NZSwift/GymWorkoutManager#101]
![image](https://cloud.githubusercontent.com/assets/5027957/17097962/21c878d6-52b4-11e6-853c-7bba4e2445cd.png)
**After push return it doesnt hide keyboard**

![image](https://cloud.githubusercontent.com/assets/5027957/17097978/36edb424-52b4-11e6-8383-0cee448a07e9.png)
**you cant selected gender now. It should be button background color changed(GWMPurple) when user selected.**

**Comment by zhangyunchen** [comment]
I can't understand the first issue about the keyboard

**Comment by iceman201** [comment]
_After push return it doesnt hide keyboard_

see the return key on the keyboard?

**Comment by zhangyunchen** [comment]
fix the two bugs above
