### ISSUE TITLE
GWM-009-Pass data to FirstViewController(Timer)

### ISSUE THREAD

**Issue by iceman201** [NZSwift/GymWorkoutManager#16]
details comments on TODO marks
Pass the time which setup on TimeSetupViewController to receivedTime of FirstViewController

the formate of time return is ['min','sec','round']

after pass through data to FirstViewController it's should display on the view
![image](https://cloud.githubusercontent.com/assets/5027957/12406523/ae97ac0a-beb2-11e5-9aab-dbfc842228df.png)

**Comment by gl-lei** [comment]
OK
