### ISSUE TITLE
GWM-011-Make round works

### ISSUE THREAD

**Issue by iceman201** [NZSwift/GymWorkoutManager#22]
currently round number doesnt work

**Comment by iceman201** [comment]
#回合数不掉  @gl-Lei 
- ![image](https://cloud.githubusercontent.com/assets/5027957/12468393/104cc3cc-c048-11e5-8634-d8a8137809a0.png)
  - 当设置time之后点击Go
- ![image](https://cloud.githubusercontent.com/assets/5027957/12468404/1bf0258e-c048-11e5-857e-03d61fe3fc30.png)
  - 时间跑到00:00:00的时候，around应该是减去一个，然后上面的时间再从3秒钟开始就是最初设置的时间
- 当回合数到0 并且跑完最后的预定时间，所有东西结束

**Comment by gl-lei** [comment]
The timeCounter and the totalTimerCounter should be the same.
