### ISSUE TITLE
GWM-016-Make each round auto stop

### ISSUE THREAD

**Issue by iceman201** [NZSwift/GymWorkoutManager#34]
- 用户在做完一组运动时候，应该有休息时间，这段时间应该是不计算在内的，所以应该是一圈完成之后，自动停止，让用户去再开始做第二圈。

**Comment by gl-lei** [comment]
OK

**Comment by iceman201** [comment]
停止之后button变回Go！，然后再点再继续

**Comment by gl-lei** [comment]
为什么分支提交不上呢？
![image](https://cloud.githubusercontent.com/assets/11263880/12706487/5199387a-c8c1-11e5-91cf-8706a589655f.png)

**Comment by iceman201** [comment]
显示的是你验证没通过，你最好在github这个project设置里把你的ssh key加到developer key那里

**Comment by gl-lei** [comment]
解决了，发现是之前将本地的remote url修改为SSH的方式之后，GitHub Desktop客户端自动生成的SSH证书不起作用了，将其删除后，再使用GitHub Desktop客户端登陆一下就解决了。
