### ISSUE TITLE
"GO" button error

### ISSUE THREAD

**Issue by iceman201** [NZSwift/GymWorkoutManager#82]
![image](https://cloud.githubusercontent.com/assets/5027957/15445997/7b1fb7d8-1f64-11e6-9f5a-1c471ccab307.png)
In the TimerViewController, if user click Go straightway without setup anything, Timer still play success sounds.
Success sounds only play when user finished "rounds"

Expect: an AlertView could alert message to user make her setup time.

**Comment by zyunchen** [comment]
complete
